# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from tf import tf_pb2 as tf__pb2


class ImmediatePredictorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ImmediatePred = channel.unary_unary(
                '/ImmediatePredictor/ImmediatePred',
                request_serializer=tf__pb2.Image.SerializeToString,
                response_deserializer=tf__pb2.Prediction.FromString,
                )


class ImmediatePredictorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ImmediatePred(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImmediatePredictorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ImmediatePred': grpc.unary_unary_rpc_method_handler(
                    servicer.ImmediatePred,
                    request_deserializer=tf__pb2.Image.FromString,
                    response_serializer=tf__pb2.Prediction.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ImmediatePredictor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImmediatePredictor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ImmediatePred(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ImmediatePredictor/ImmediatePred',
            tf__pb2.Image.SerializeToString,
            tf__pb2.Prediction.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
