# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tf_fast.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from tf import tf_pb2 as tf__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='tf_fast.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rtf_fast.proto\x1a\x08tf.proto2<\n\x12ImmediatePredictor\x12&\n\rImmediatePred\x12\x06.Image\x1a\x0b.Prediction\"\x00\x62\x06proto3'
  ,
  dependencies=[tf__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_IMMEDIATEPREDICTOR = _descriptor.ServiceDescriptor(
  name='ImmediatePredictor',
  full_name='ImmediatePredictor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=27,
  serialized_end=87,
  methods=[
  _descriptor.MethodDescriptor(
    name='ImmediatePred',
    full_name='ImmediatePredictor.ImmediatePred',
    index=0,
    containing_service=None,
    input_type=tf__pb2._IMAGE,
    output_type=tf__pb2._PREDICTION,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMMEDIATEPREDICTOR)

DESCRIPTOR.services_by_name['ImmediatePredictor'] = _IMMEDIATEPREDICTOR

# @@protoc_insertion_point(module_scope)
