# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from tf import tf_pb2 as tf__pb2


class CommunicatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RequestImages = channel.unary_unary(
                '/Communicator/RequestImages',
                request_serializer=tf__pb2.TFStandard.SerializeToString,
                response_deserializer=tf__pb2.ImageArray.FromString,
                )
        self.PostPredictions = channel.unary_unary(
                '/Communicator/PostPredictions',
                request_serializer=tf__pb2.PredictionArray.SerializeToString,
                response_deserializer=tf__pb2.TFStandard.FromString,
                )


class CommunicatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RequestImages(self, request, context):
        """ask for new images to predict
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PostPredictions(self, request, context):
        """exchange the prediction results
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommunicatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RequestImages': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestImages,
                    request_deserializer=tf__pb2.TFStandard.FromString,
                    response_serializer=tf__pb2.ImageArray.SerializeToString,
            ),
            'PostPredictions': grpc.unary_unary_rpc_method_handler(
                    servicer.PostPredictions,
                    request_deserializer=tf__pb2.PredictionArray.FromString,
                    response_serializer=tf__pb2.TFStandard.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Communicator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Communicator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RequestImages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Communicator/RequestImages',
            tf__pb2.TFStandard.SerializeToString,
            tf__pb2.ImageArray.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PostPredictions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Communicator/PostPredictions',
            tf__pb2.PredictionArray.SerializeToString,
            tf__pb2.TFStandard.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
